### PR TITLE
Added function to get the current trends

### PR DESCRIPTION
**Pull request by tensarflow**
Simply import `get_trends` from `twitter_scraper` and call `get_trends`. Sample usage:

```
from twitter_scraper import get_trends

print (get_trends())
```

Should be added to the documentation..

### CODE REVIEW

**Comment by tensarflow** [comment]
Updated the documentation

**Comment by bisguzar** [comment]
Hi @tensarflow  its awesome idea! I refactored your code a bit. Can you review it? If you think anything wrong please commit before merging. 

We built this project on requests_html, so we can use it instead of beautifulsoup already.

**Comment by tensarflow** [comment]
I just tested it. Works perfect. 
Nice work :)

**Comment by bisguzar** [comment]
Honors to you, thanks again ^^

**Pull request merged**
