### PR TITLE
Add Headers for Trends Request, #108

### PR DESCRIPTION
**Pull request by bisguzar**

### CODE REVIEW

**Comment by zachadams16** [comment]
looks good

**Comment by Sue-Fwl** [comment]
Greetings,

I'm getting an error on  -> 'module_html' when calling 'get_trends()'

`Traceback (most recent call last):

  in <module>
    Trending = get_trends()

  File "site-packages\twitter_scraper\modules\trends.py", line 17, in get_trends
    html = html.json()["module_html"]

KeyError: 'module_html'`

**Comment by bisguzar** [comment]
Hi @Sue-Fwl , you are using the latest version, right? Please be sure. Thanks

**Comment by Sue-Fwl** [comment]
Sure did, and I just copied the trends.py file from the repository  and ran the command again [same error {KeyError: 'module_html'} ] 

p.s other modules are working great for me -profile and tweets-

**Comment by Sue-Fwl** [comment]
I'm not sure~
Will do then.

**Pull request merged**
