### PR TITLE
Fix some bug risks and code quality issues

### PR DESCRIPTION
**Pull request by mohi7solanki**
Changes:
 - Fix undefined name error in __process_paragraph method
 - Remove some unused imports
 - Add .deepsource.toml file to file to run continuous static analysis on the repository with DeepSource

This PR also adds .deepsource.toml configuration file to run static analysis continuously on the repo with DeepSource. Upon enabling DeepSource, quality and security analysis will be run on every PR to detect 500+ types of problems in the changes — including bug risks, anti-patterns, security vulnerabilities, etc.

DeepSource is free to use for open-source projects, and is used by teams at NASA, Uber, Slack among many others, and open-source projects like ThoughtWorks/Gauge, Masonite Framework, etc.

To enable DeepSource analysis after merging this PR, please follow these steps:

- [Sign up](https://deepsource.signup) on DeepSource with your GitHub account and grant access to this repo.
- Activate analysis on this repo [here](https://deepsource.io/dashboard/gh/bisguzar/activate-repo/).
- You can also look at the [docs](https://deepsource.io/docs) for more details. Do let me know if I can be of any help!

### CODE REVIEW

**Comment by bisguzar** [comment]
Thanks for PR, I was working on new version of Profile class. Can you check branch **improvement/profile-class** ?

**Comment by mohi7solanki** [comment]
@bisguzar I ran analysis on **improvement/profile-class** most of the issues are fixed, you can see the [result](https://deepsource.io/gh/mohi7solanki/twitter-scraper/)

**Comment by bisguzar** [comment]
Got it, but this PR has conflicts now. As I said I updated Profile.py recently. If you revert your commits which one effects on profile.py or resolve conflicts, I can merge it succesfully. Thanks again for your efforts

**Comment by mohi7solanki** [comment]
@bisguzar I have resolved conflicts

**Comment by bisguzar** [comment]
Thanks again, I'm merging it. I will deep search this tool and optimize it asap 🎉🎉

**Pull request merged**
