### PR TITLE
Add documentation/KO directory and add Korea doc.

### PR DESCRIPTION
**Pull request by lionking6792**
I added '**documentation/KO**' directory and add Korean version of '**README.md** 'to '**documentation/KO**'.
I worked in **improvement/new-readme** branch! 

If i haven't catch anything that PR requirements, please comment me!

Thank you! and I hope this will be merge!!

Thanks :)

### CODE REVIEW

**Comment by bisguzar** [comment]
Please feel free to adding your name to **contributors** section as translator. I will merge it after full translation. Thank you so much ^^

**Comment by lionking6792** [comment]
I really Thanks, I'm honored to be in your commiter!!!
I have just little question.

First,

Today, I translated two more things **LICENSE**, and annotation of **setup.py**.
But, nothing else are including annotations.

Do you want to translate almost everything to translate version ( eg. print('translated version') )
or just **LICENSE**, **setup.py** , **readme.md** ?

Second,

If you want just **LICENSE**, **setup.py** and **readme.md**,
Do you want to include all repository's files on translated directory or
just translated files?

I'll respect your opinion and PR to you!

Really thanks for comment for my PR!! ^^

**Comment by lionking6792** [comment]
I added all Korean tranlated version of this repository!!

Thank you for giving me the chance to translate!
I hope this would be merge!!

Really appreciate to you and thanks!

**Comment by bisguzar** [comment]
Hi @lionking6792 , I was a bit busy. I added missing lines finally. Can you translate them too? And what do you think about creating a docs folder in root and move your readme to there as language code like en_GB.md.

And we are not have to translate comment lines. We can not storage source files for every language :/

**Comment by lionking6792** [comment]
Hi @bisguzar , I agree about your idea! I'll do it 10 hours later after I sleep! Korea is 4 a.m. now. :)

And, I'll add new PR for that!! Thank you for your comment! I'm little bit busy next week, so I hope you see new PR within this week. 

Thanks :)

**Comment by lionking6792** [comment]
I PR new one right now! Please check it!!

**Comment by bisguzar** [comment]
resume in #85

**Pull request closed without merging**
